site_name: Bruno Docs
repo_url: https://github.com/usebruno/bruno-docs

nav:
  - "Introduction": 
    - "Bruno": "index.md"
    - "Index": "table-of-contents.md"
    - "Manifesto": "manifesto.md"
    - "Support": "support.md"
  - "Bru Lang":
    - "Overview": "bru-lang-overview.md"
    - "Samples": "bru-language-samples.md"
    - "Language": "bru-language-design.md"
    - "Tag Reference": "bru-language-tag-reference.md"
    - "Syntax Highlighting": "bru-lang-extensions.md"
  - "Bru CLI":
    - "Overview": "cli/overview.md"
  - "Secrets Management":
    - "Overview": "secrets-management/overview.md"
    - "DotEnv Files": "secrets-management/dotenv-file.md"
    - "Secret Variables": "secrets-management/secret-variables.md"
  - "Scripting":
    - "Getting Started": "scripting/introduction.md"
    - "Vars": "scripting/vars.md"
    - "Response Query": "scripting/response-query.md"
    - "Inbuilt Libraries": "scripting/inbuilt-libraries.md"
    - "External Libraries": "scripting/external-libraries.md"
    - "Sync Requests": "scripting/sync-requests.md"
    - "JavaScript Reference": "scripting/javascript-reference.md"
  - "Testing":
    - "Getting Started": "testing/introduction.md"
    - "Assertions": "testing/assertions.md"
    - "JavaScript Reference": "testing/javascript-reference.md"

theme:
  name: material
  logo: assets/bruno.svg
  favicon: assets/logo-transparent.png
  palette:
  # Palette toggle for Automatic Mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to Light Mode
  # Palette toggle for Light Mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to Dark Mode
  # Palette toggle for Dark Mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to Light Mode
  features:
    - navigation.footer

extra:
  social:
    - icon: fontawesome/solid/road
      link: https://github.com/usebruno/bruno/discussions/384
      name: Roadmap
    - icon: fontawesome/solid/people-group
      link: https://github.com/usebruno/bruno/discussions/343
      name: Testimonials
    - icon: fontawesome/solid/globe
      link: https://www.usebruno.com/
      name: Website
    - icon: fontawesome/solid/download
      link: https://www.usebruno.com/downloads
      name: Downloads
    - icon: fontawesome/brands/github
      link: https://github.com/usebruno/bruno
      name: GitHub

extra_css:
  - extra.css